# Generated by Django 5.1.3 on 2024-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='end_time',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='start_time',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expose',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
