# Generated by Django 5.1.3 on 2025-01-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='amounth',
            new_name='amount',
        ),
    ]
