# Generated by Django 5.1.3 on 2025-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0002_rename_amounth_transition_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='statuse',
            field=models.CharField(choices=[('expose', 'income')], default='expose', max_length=200),
        ),
    ]
