# Generated by Django 5.1.3 on 2025-01-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0002_sort_category_end_time_category_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('amounth', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expose',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sort',
        ),
        migrations.RemoveField(
            model_name='category',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='start_time',
        ),
        migrations.AddField(
            model_name='transitions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transitions.category'),
        ),
        migrations.DeleteModel(
            name='Expose',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
