# Generated by Django 5.1.3 on 2025-01-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transitions', '0006_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='category',
            field=models.CharField(choices=[('expose', 'income')], default='expose', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
